import type { ProductCardItem, ProductDetail, RecommendationResponse } from "../types/recommendation";

const scoreBreakdown = {
  ingredient_effect_score: 28,
  ingredient_evidence_score: 24,
  skin_type_match_score: 18,
  price_value_score: 14,
  keyword_score: 8,
  vector_score: 7,
  search_match_score: 9,
  risk_penalty: 0,
};

export const fallbackProductDetails: ProductDetail[] = [
  {
    product_id: "10",
    rank: 1,
    total_score: 90,
    reason_summary: "보습, 진정, 장벽 케어 성분을 중심으로 확인한 원본 샘플 상품입니다.",
    brand: "라로슈포제",
    name: "라로슈포제 시카플라스트 밤 B5+ 100ml 기획 (+3ml 추가증정)",
    thumbnail_url: null,
    lowest_price: 34850,
    evidence_tags: ["판테놀", "마데카소사이드", "글리세린"],
    key_ingredients: ["판테놀", "마데카소사이드", "글리세린", "시어버터"],
    risk_flags: [],
    score_breakdown: scoreBreakdown,
    image_urls: [],
    content_confidence: "medium",
    related_ingredients: ["판테놀", "마데카소사이드", "글리세린", "시어버터"],
    purchase_url: null,
    evidence: [
      {
        ingredient_name: "판테놀",
        effect_name: "장벽",
        evidence_level: "medium",
        evidence_text: "피부 장벽과 진정 케어 목적의 성분으로 확인했습니다.",
        source_title: "원본 디자인 샘플 데이터",
      },
      {
        ingredient_name: "마데카소사이드",
        effect_name: "진정",
        evidence_level: "medium",
        evidence_text: "민감한 피부의 진정 케어 맥락에서 확인했습니다.",
        source_title: "원본 디자인 샘플 데이터",
      },
    ],
    prices: [],
    sources: [],
  },
  {
    product_id: "12",
    rank: 2,
    total_score: 94,
    reason_summary: "속건조와 보습 고민에 맞춰 히알루론산 계열 성분을 우선 확인한 샘플 상품입니다.",
    brand: "웰라쥬",
    name: "[속건조필수템] 웰라쥬 리얼 히알루로닉 블루 100 앰플 75ml 2입 기획",
    thumbnail_url: null,
    lowest_price: 29800,
    evidence_tags: ["판테놀", "히알루론산", "글리세린"],
    key_ingredients: ["판테놀", "소듐하이알루로네이트", "글리세린"],
    risk_flags: [],
    score_breakdown: { ...scoreBreakdown, ingredient_effect_score: 30 },
    image_urls: [],
    content_confidence: "medium",
    related_ingredients: ["판테놀", "소듐하이알루로네이트", "글리세린", "프로판다이올"],
    purchase_url: null,
    evidence: [
      {
        ingredient_name: "소듐하이알루로네이트",
        effect_name: "보습",
        evidence_level: "medium",
        evidence_text: "피부 수분 유지에 연결되는 보습 성분으로 확인했습니다.",
        source_title: "원본 디자인 샘플 데이터",
      },
      {
        ingredient_name: "판테놀",
        effect_name: "진정",
        evidence_level: "medium",
        evidence_text: "진정과 장벽 케어 목적의 성분으로 확인했습니다.",
        source_title: "원본 디자인 샘플 데이터",
      },
    ],
    prices: [],
    sources: [],
  },
  {
    product_id: "15",
    rank: 3,
    total_score: 92,
    reason_summary: "수분, 보습, 진정 고민에 맞춰 자작나무 수분 크림 샘플을 표시합니다.",
    brand: "라운드랩",
    name: "[6월올영픽/총200ml] 라운드랩 자작나무 수분 크림 80ml+80ml 더블 기획 (+40ml)",
    thumbnail_url: null,
    lowest_price: 24600,
    evidence_tags: ["판테놀", "히알루론산", "글리세린"],
    key_ingredients: ["자작나무수액", "판테놀", "글리세린", "히알루론산"],
    risk_flags: [],
    score_breakdown: { ...scoreBreakdown, price_value_score: 16 },
    image_urls: [],
    content_confidence: "medium",
    related_ingredients: ["자작나무수액", "판테놀", "글리세린", "히알루론산"],
    purchase_url: null,
    evidence: [
      {
        ingredient_name: "글리세린",
        effect_name: "보습",
        evidence_level: "medium",
        evidence_text: "피부 보습과 수분 유지 목적의 기본 보습 성분으로 확인했습니다.",
        source_title: "원본 디자인 샘플 데이터",
      },
      {
        ingredient_name: "판테놀",
        effect_name: "장벽",
        evidence_level: "medium",
        evidence_text: "장벽 케어와 진정 목적의 성분으로 확인했습니다.",
        source_title: "원본 디자인 샘플 데이터",
      },
    ],
    prices: [],
    sources: [],
  },
];

export const fallbackProductCards: ProductCardItem[] = fallbackProductDetails.map((product) => ({
  product_id: product.product_id,
  rank: product.rank,
  total_score: product.total_score,
  reason_summary: product.reason_summary,
  brand: product.brand,
  name: product.name,
  thumbnail_url: product.thumbnail_url,
  lowest_price: product.lowest_price,
  evidence_tags: product.evidence_tags,
  key_ingredients: product.key_ingredients,
  risk_flags: product.risk_flags,
  score_breakdown: product.score_breakdown,
}));

export const getFallbackProductDetail = (productId: string) =>
  fallbackProductDetails.find((product) => product.product_id === productId) ?? null;

export const createFallbackRecommendation = (
  concernText: string,
  profile: { skin: string; sensitivity: string },
): RecommendationResponse => ({
  recommendation_id: "fallback-original-design",
  summary: {
    concern_text: concernText,
    skin_type: profile.skin,
    sensitivity: profile.sensitivity,
    avoid_ingredients: [],
    concerns: [concernText],
    effects: ["보습", "진정", "장벽"],
    purchase_constraints: {
      categories: [],
      brands: [],
      price_min: null,
      price_max: null,
      price_text: null,
      price_max_text: null,
    },
  },
  unmatched_terms: [],
  products: fallbackProductCards,
  pagination: {
    page: 1,
    page_size: fallbackProductCards.length,
    total_items: fallbackProductCards.length,
    total_pages: 1,
    has_next: false,
    has_prev: false,
  },
});
